name: Update index.md

on:
  push:
    branches:
      - main  
  workflow_dispatch:


jobs:
  update_index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.3

    - name: Run generate_index.py
      run: |
        python3 generate_index.py
        git config --local user.email "Viren070@users.noreply.github.com"
        git config --local user.name "Viren070"
        git add index.md
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          echo "Pushing changes"
          git commit -m "Update index.md"
          git push
        fi
