name: Update index.md

on:
  push:
    branches:
      - main  

jobs:
  update_index:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Run generate_index.py
      run: |
        python generate_index.py
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.md
        git commit -m "Update index.md"
        git push
